project_id = "zspbzfyruogyugizehhw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"
enable_signup = true
email_double_confirm_changes = true
enable_anonymous_sign_ins = false

[db]
port = 54322

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
buckets = []

[functions.search-products]
verify_jwt = false

[edge_runtime]
enabled = true
ip_version = "ipv4"
policy = "per_worker"
inspector_port = 8083

[analytics]
enabled = false
port = 54327