[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322

[functions.search-products]
verify_jwt = false

[functions.suggest-items]
verify_jwt = false

[functions.classify-nova]
verify_jwt = false

[functions.parse-recipe]
verify_jwt = false

[functions.get-product-details]
verify_jwt = false
